language: node_js
sudo: required
dist: trusty
node_js:
  - "0.10"
services:
  - docker
before_install:
  - docker pull mysql
  - docker run --name mysql-56 -v test/travis/my_5.6_conf:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=numtel -d mysql:5.6 -p 3356:3306
script:
  - ./test/travis/runner.sh
